### ISSUE TITLE
P4 to C compilation fails with syntax error

### ISSUE THREAD

**Issue by MarcusWichelmann** [P4ELTE/t4p4s#26]
Hi,

I tried running the examples and got the following error:
```
root@ddos-test:~/t4p4s# ./t4p4s.sh ./examples/l2fwd-gen.p4 
[COMPILE  P4-16] ./examples/l2fwd-gen.p4 @std
Traceback (most recent call last):
  File "src/compiler.py", line 8, in <module>
    from hlir16.hlir import *
  File "/root/t4p4s/src/hlir16/hlir.py", line 14, in <module>
    from hlir16.p4node import P4Node
  File "/root/t4p4s/src/hlir16/p4node.py", line 115
    return ((key, subnode) for key in node if (subnode := node[key]) not in founds)
                                                       ^
SyntaxError: invalid syntax

Error: P4 to C compilation failed (error code: 1)
```

Any idea?

**Comment by scholzd** [comment]
Assignment expressions are a new feature in python 3.8 (https://www.python.org/downloads/release/python-380/).
You probably need to upgrade your python version if you want to use any of the hlir16 commits using this new syntax.

Best regards.

**Comment by MarcusWichelmann** [comment]
Thank you, it works with Python 3.9. 👍🏼
